'use strict';

const mongoose = require('mongoose');

/**
 * Minimal Report Schema:
 * Stores ONLY the final statutory PDF report generated by ComplianceEngine
 * along with its Cloudinary URL for the mobile application to fetch and render.
 */
const ReportSchema = new mongoose.Schema(
  {
    reportId: { type: String, required: true, unique: true, index: true },
    reference_no: { type: String, default: null }, // Backwards compatibility with legacy queries
    productId: { type: String, default: null, index: true },
    pdfUrl: { type: String, required: true },
    cloudinaryUrl: { type: String, default: null },
    productName: { type: String, default: 'Package Report' },
    status: { type: String, default: null }, // COMPLIANT, NON-COMPLIANT, or EXEMPT
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Report', ReportSchema);
