/**
 * pipeline/stage8_report.js
 * Builds the final compliance/non-compliance PDF report from the
 * Stage 6 rule-engine result. Uses the dependency-free simplePdfWriter
 * (see utils/simplePdfWriter.js) — swap for `pdfkit` there if you need
 * embedded evidence photos, logos, or richer layout.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { generatePdfBuffer, FONT_HEADING_SIZE, FONT_SUBHEADING_SIZE } = require('../utils/simplePdfWriter');
const { ensureDirs } = require('../utils/fileHelpers');
const config = require('../config');
const logger = require('../utils/logger');

const SEVERITY_LABEL = { critical: 'CRITICAL', major: 'MAJOR', minor: 'MINOR' };

function buildReportBlocks({ imagePath, packageRecord, complianceResult }) {
  const blocks = [];
  const now = new Date().toISOString();

  blocks.push({ text: config.report.orgName, size: FONT_HEADING_SIZE, bold: true });
  blocks.push({ text: 'Legal Metrology (Packaged Commodities) Compliance Report', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 4 });
  blocks.push({ text: `Generated: ${now}`, size: 9, gapBefore: 4 });
  blocks.push({ text: `Source image: ${path.basename(imagePath)}`, size: 9 });

  blocks.push({ text: 'Product Details', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 16 });
  blocks.push({ text: `Category: ${packageRecord.commodity.category || 'Unclassified'}`, size: 10, gapBefore: 4 });
  const qty = packageRecord.commodity.netQuantityValue;
  const unit = packageRecord.commodity.netQuantityUnit;
  blocks.push({ text: `Declared net quantity: ${qty != null ? `${qty}${unit || ''}` : 'Not detected'}` , size: 10});
  blocks.push({ text: `MRP declared: ${packageRecord.declarations.mrp.present ? 'Yes' : 'NOT FOUND'}`, size: 10 });
  blocks.push({ text: `Manufacturer declared: ${packageRecord.declarations.manufacturer.present ? 'Yes' : 'NOT FOUND'}`, size: 10 });

  if (!complianceResult.applicable) {
    blocks.push({ text: 'Applicability', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 16 });
    blocks.push({ text: `These Rules do not apply to this package.`, size: 10, gapBefore: 4 });
    blocks.push({ text: `Reason: ${complianceResult.exemptionReason}`, size: 10 });
    return blocks;
  }

  blocks.push({ text: 'Compliance Summary', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 16 });
  blocks.push({
    text: complianceResult.compliant
      ? 'OVERALL STATUS: COMPLIANT — no violations detected.'
      : `OVERALL STATUS: NON-COMPLIANT — ${complianceResult.summary.total} violation(s) found (${complianceResult.summary.critical} critical, ${complianceResult.summary.major} major, ${complianceResult.summary.minor} minor).`,
    size: 10,
    bold: !complianceResult.compliant,
    gapBefore: 4,
  });

  if (complianceResult.violations.length > 0) {
    blocks.push({ text: 'Violations', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 16 });
    complianceResult.violations
      .sort((a, b) => {
        const order = { critical: 0, major: 1, minor: 2 };
        return order[a.severity] - order[b.severity];
      })
      .forEach((viol, idx) => {
        blocks.push({
          text: `${idx + 1}. [${SEVERITY_LABEL[viol.severity]}] ${viol.rule} — ${viol.message}`,
          size: 10,
          gapBefore: 6,
        });
      });
  }

  blocks.push({ text: 'Note', size: FONT_SUBHEADING_SIZE, bold: true, gapBefore: 16 });
  blocks.push({
    text:
      'This report is generated by an automated image-based compliance pipeline. Registration status (Rules 27-30) and penalty determination (Rule 32) require a manual/database cross-check and are not covered by this automated report.',
    size: 9,
    gapBefore: 4,
  });

  return blocks;
}

async function generateReport({ imagePath, packageRecord, complianceResult, productDir }) {
  ensureDirs(productDir);
  const blocks = buildReportBlocks({ imagePath, packageRecord, complianceResult });
  const pdfBuffer = generatePdfBuffer(blocks);

  const outFile = path.join(productDir, 'report.pdf');
  fs.writeFileSync(outFile, pdfBuffer);
  logger.info('stage8_report', `Report written: ${outFile}`);
  return outFile;
}

module.exports = { generateReport, buildReportBlocks };
