module.exports = {
  apps: [
    {
      name: 'lmv-admin-backend',
      script: 'src/index.js',
      cwd: './admin-backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        ADMIN_BACKEND_PORT: 4001,
      },
      error_file: '../logs/admin-backend-err.log',
      out_file: '../logs/admin-backend-out.log',
      time: true,
    },
    {
      name: 'lmv-senior-inspector-backend',
      script: 'src/index.js',
      cwd: './senior-inspector-backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        SENIOR_INSPECTOR_BACKEND_PORT: 4002,
      },
      error_file: '../logs/senior-inspector-backend-err.log',
      out_file: '../logs/senior-inspector-backend-out.log',
      time: true,
    },
    {
      name: 'lmv-webhook-listener',
      script: 'deploy/webhook-server.js',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        WEBHOOK_PORT: 4005,
      },
      error_file: './logs/webhook-listener-err.log',
      out_file: './logs/webhook-listener-out.log',
      time: true,
    },
    {
      name: 'lmv-local-scraper',
      script: 'server.js',
      cwd: '../lmVerify/local-scraper',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
      },
      error_file: './logs/local-scraper-err.log',
      out_file: './logs/local-scraper-out.log',
      time: true,
    },
  ],
};
